- name: enable and restart carbon-cache
  service: name=carbon-cache enabled=yes state=restarted

- name: enable and restart grafana
  service: name=grafana-server enabled=yes state=restarted

- name: restart nginx
  service: name=nginx state=restarted

- name: restart uwsgi
  service: name=uwsgi state=restarted
