version: '2.3'
services:
  geth:
    build:
      context: .
      dockerfile: Dockerfile-geth
    volumes:
      - ./geth:/home/PirateCoin
    restart: on-failure
    ports:
      - "30303:30303"
    cpu_count: 1
    cpu_percent: 50
    mem_limit: 2g
    mem_reservation: 1g
  piratecoin:
    build: .
    volumes:
      - ./mono_service:/home/PirateCoin
    depends_on:
      - geth
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 128m
    ports:
      - "14473:14473"
