version: '2.3'
services:
  treasuremap:
    build: .
    volumes:
      - .:/home/TreasureMap
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 128m
  nginx:
    image: nginx:1.13.7-alpine
    ports:
      - "7483:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/default:/etc/nginx/sites-enabled/default
      - .:/home/TreasureMap
    depends_on:
      - treasuremap
    restart: on-failure
    mem_limit: 256m
    mem_reservation: 64m

